apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: www.sgerd.com
      http:
        paths:
          - path: /api/usuario/?(.*)
            backend:
              serviceName: autorizador-srv
              servicePort: 3000
          - path: /api/empresa/?(.*)
            backend:
              serviceName: empresa-srv
              servicePort: 3000
          - path: /api/establecimiento/?(.*)
            backend:
              serviceName: establecimiento-srv
              servicePort: 3000
          - path: /api/almacen/?(.*)
            backend:
              serviceName: almacen-srv
              servicePort: 3000
          - path: /api/producto/?(.*)
            backend:
              serviceName: producto-srv
              servicePort: 3000
          - path: /api/permiso/?(.*)
            backend:
              serviceName: permiso-srv
              servicePort: 3000
          - path: /api/unidadmedida/?(.*)
            backend:
              serviceName: unidad-medida-srv
              servicePort: 3000
          - path: /api/producto/manejadorprecio/?(.*)
            backend:
              serviceName: manejador-precio-srv
              servicePort: 3000
          - path: /api/categoria/producto/?(.*)
            backend:
              serviceName: categoria-srv
              servicePort: 3000
          - path: /api/empresa/proveedor/?(.*)
            backend:
              serviceName: proveedor-srv
              servicePort: 3000
          - path: /api/empresa/cliente/?(.*)
            backend:
              serviceName: cliente-srv
              servicePort: 3000
          - path: /api/compra/?(.*)
            backend:
              serviceName: compra-srv
              servicePort: 3000
          - path: /api/stock/?(.*)
            backend:
              serviceName: stock-srv
              servicePort: 3000
          - path: /api/venta/?(.*)
            backend:
              serviceName: venta-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: front-srv
              servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
    service.beta.kubernetes.io/do-loadbalancer-hostname: 'www.sgerd.com'
  labels:
    helm.sh/chart: ingress-nginx-2.0.3
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
