apiVersion: apps/v1
kind: Deployment
metadata:
  name: autorizador-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autorizador
  template:
    metadata:
      labels:
        app: autorizador
    spec:
      containers:
        - name: autorizador
          image: eloyk/autorizador
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: 'mongodb://autorizador-mongo-srv:27017/autorizador'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: autorizador-srv
spec:
  selector:
    app: autorizador
  ports:
    - name: autorizador
      protocol: TCP
      port: 3000
      targetPort: 3000
