apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
        - name: cliente
          image: eloyk/cliente
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: 'mongodb://cliente-mongo-srv:27017/cliente'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: cliente-srv
spec:
  selector:
    app: cliente
  ports:
    - name: cliente
      protocol: TCP
      port: 3000
      targetPort: 3000
