apiVersion: apps/v1
kind: Deployment
metadata:
  name: compra-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compra
  template:
    metadata:
      labels:
        app: compra
    spec:
      containers:
        - name: compra
          image: eloyk/compra
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: 'mongodb://compra-mongo-srv:27017/compra'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: compra-srv
spec:
  selector:
    app: compra
  ports:
    - name: compra
      protocol: TCP
      port: 3000
      targetPort: 3000
