apiVersion: apps/v1
kind: Deployment
metadata:
  name: establecimiento-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: establecimiento
  template:
    metadata:
      labels:
        app: establecimiento
    spec:
      containers:
        - name: establecimiento
          image: eloyk/establecimiento
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: "mongodb://establecimiento-mongo-srv:27017/establecimiento"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: establecimiento-srv
spec:
  selector:
    app: establecimiento
  ports:
    - name: establecimiento
      protocol: TCP
      port: 3000
      targetPort: 3000
