apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiracion-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiracion
  template:
    metadata:
      labels:
        app: expiracion
    spec:
      containers:
        - name: expiracion
          image: eloyk/expiracion
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: REDIS_HOST
              value: expiracion-redis-srv
