apiVersion: apps/v1
kind: Deployment
metadata:
  name: factura-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factura
  template:
    metadata:
      labels:
        app: factura
    spec:
      containers:
        - name: factura
          image: eloyk/factura
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: "mongodb://factura-mongo-srv:27017/factura"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: factura-srv
spec:
  selector:
    app: factura
  ports:
    - name: factura
      protocol: TCP
      port: 3000
      targetPort: 3000
