apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proveedor
  template:
    metadata:
      labels:
        app: proveedor
    spec:
      containers:
        - name: proveedor
          image: eloyk/proveedor
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: 'mongodb://proveedor-mongo-srv:27017/proveedor'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: proveedor-srv
spec:
  selector:
    app: proveedor
  ports:
    - name: proveedor
      protocol: TCP
      port: 3000
      targetPort: 3000
