apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: eloyk/stock
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: sgan
            - name: MONGO_URI
              value: "mongodb://stock-mongo-srv:27017/stock"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: stock-srv
spec:
  selector:
    app: stock
  ports:
    - name: stock
      protocol: TCP
      port: 3000
      targetPort: 3000
