const TYPES = {
  ASIDE_TOGGLE: "ASIDE_TOGGLE",
  ASIDE_CHANGE: "ASIDE_CHANGE",
  BREADCRUMB_CHANGE: "BREADCRUMB_CHANGE",
  PAGE_CHANGE_HEADER_TITLE: "PAGE_CHANGE_HEADER_TITLE",
  PAGE_CHANGE_THEME: "PAGE_CHANGE_THEME",
  SIDEMENU_TOGGLE: "SIDEMENU_TOGGLE",
  SIDEMENU_CHANGE: "SIDEMENU_CHANGE",
  CURRENT_USER_CHANGE: "CURRENT_USER_CHANGE",
}

export default TYPES
