name: deploy-unidad-medida

on:
  push:
    branches: 
      - master
    paths:
      - 'unidad-medida/**'

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd unidad-medida && docker build -t eloyk/unidad-medida .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push eloyk/unidad-medida
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save sgan
      - run: kubectl rollout restart deployment unidad-medida-depl
