name: deploy-autorizador

on:
  push:
    branches: 
      - master
    paths:
      - 'autorizador/**'

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd autorizador && docker build -t eloyk/autorizador .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push eloyk/autorizador
