name: tests

on:
  pull_request:
    paths:
      - 'autorizador/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd autorizador && npm install && npm run test:ci
